export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  KASIR: '/kasir',
  PRODUCTS: '/products',
  SUPPLIERS: '/suppliers',
  SUPPLIER_PURCHASES: '/suppliers/purchases',
  SUPPLIER_RETURNS:   '/suppliers/returns',
  TRANSACTIONS: '/transactions',
  CUSTOMERS: '/customers',
  RECEIVABLES: '/receivables',
  FINANCE: '/finance',
  FINANCE_CASH_DRAWER: '/finance/cash-drawer',
  FINANCE_EXPENSES: '/finance/expenses',
  FINANCE_MY_CASH: '/finance/my-cash',
  REPORTS: '/reports',
  SHIFTS: '/shifts',
  SETTINGS: '/settings',
  SYNC: '/sync',
} as const
